version: 2

jobs:
  build:
    docker:
    - image: tendermint/kms:build-2019-06-05-v0 # bump cache keys when modifying this
    environment:
      RUSTFLAGS: -D warnings
    steps:
    - checkout
    - restore_cache:
        key: cache-2019-06-05-v0 # bump save_cache key below too
    - run:
        name: Install Rust 1.36.0 # TODO: update Rust in the upstream Docker image
        command: |
          rustup toolchain install 1.36.0
          rustup default 1.36.0
          rustup component add rustfmt
          rustup component add clippy
    - run:
        name: rustfmt
        command: |
          cargo fmt --version
          cargo fmt --all -- --check
    - run:
        name: clippy
        command: |
          cargo clippy --version
          cargo clippy --all --exclude signatory-sodiumoxide # sodiumoxide isn't clippy-friendly
    - run:
        name: build (--no-default-features)
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features
    - run:
        name: build (default features)
        command: |
          rustc --version
          cargo --version
          cargo build
    - run:
        name: build (ecdsa feature only)
        command: |
          rustc --version
          cargo --version
          cargo build --features=ecdsa
    - run:
        name: build (ed25519 feature only)
        command: |
          rustc --version
          cargo --version
          cargo build --features=ed25519
    - run:
        name: build (encoding feature only)
        command: |
          rustc --version
          cargo --version
          cargo build --features=encoding
    - run:
        name: build (--no-default-features + ecdsa + ed25519 + encoding + pkcs8)
        command: |
          rustc --version
          cargo --version
          cargo build --no-default-features --features=ecdsa,ed25519,encoding,pkcs8
    - run:
        name: build (default features + ecdsa + ed25519)
        command: |
          rustc --version
          cargo --version
          cargo build --features=ecdsa,ed25519
    - run:
        name: test (default features + ecdsa + ed25519)
        command: |
          rustc --version
          cargo --version
          cargo test --lib --features=ecdsa,ed25519,test-vectors
    - run:
        name: signatory-dalek crate
        command: |
          rustc --version
          cargo --version
          cargo build --benches --package=signatory-dalek
          cargo test --package=signatory-dalek
    - run:
        name: signatory-ring crate
        command: |
          rustc --version
          cargo --version
          cargo build --benches --package=signatory-ring
          cargo test --package=signatory-ring
    - run:
        name: signatory-secp256k1 crate
        command: |
          rustc --version
          cargo --version
          cargo build --benches --package=signatory-secp256k1
          cargo test --package=signatory-secp256k1
    - run:
        name: signatory-sodiumoxide crate
        command: |
          rustc --version
          cargo --version
          cargo build --benches --package=signatory-sodiumoxide
          cargo test --package=signatory-sodiumoxide
    - run:
        name: signatory-ledger-tm crate
        command: |
          rustc --version
          cargo --version
          cargo build --package=signatory-ledger-tm
          # Temporarily Disabling testing until a mockhsm is available
          # cd signatory-ledger-tm && cargo test
    - run:
        name: audit
        command: |
          cargo install cargo-audit --force
          cargo audit --deny-warnings --ignore RUSTSEC-2019-0031
    - save_cache:
        key: cache-2019-06-05-v0 # bump restore_cache key above too
        paths:
        - "~/.cargo"
        - "./target"
